### ISSUE TITLE
Errors at startup + fail to list artists/albums

### ISSUE THREAD

**Issue by jrlambs** [havardgulldahl/mopidy_plex#4]
Running on a pi3 with the following settings (paired down to things I think might matter):
certifi (2015.4.28)
gmusicapi (9.0.0)
Pykka (1.2.1)
Mopidy (2.0.0)
Mopidy-GMusic (1.0.0)
Mopidy-MusicBox-Webclient (2.2.0)
Mopidy-Plex (0.1.0b0)
PlexAPI (2.0.0a-..................................-.version.of.this.api)

I've installed both plexApi and mopidy-plex directly from the repositories.

on Startup I see multiple errors as listed below

2016-04-13 19:41:30,127 - ERROR    PlexBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 18, in _backend_error_handling
    yield
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 66, in as_list
    playlists = future.get()
  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(_self._data['exc_info'])
  File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(_message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Plex-0.1.0b0-py2.7.egg/mopidy_plex/mwt.py", line 73, in func
    v = self.cache[key] = f(*args,**kwargs),time.time()
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Plex-0.1.0b0-py2.7.egg/mopidy_plex/playlists.py", line 31, in as_list
    for playlist in self.plex.playlists(playlisttype='audio')]
TypeError: playlists() got an unexpected keyword argument 'playlisttype'

I do see a Pandora item in the "Browse" section which lists Artists and albums.. but clicking on each returns an empty list and the following error in the log.

2016-04-13 19:43:47,013 - ERROR    PlexBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(_self._data['exc_info'])
  File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(_message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Plex-0.1.0b0-py2.7.egg/mopidy_plex/mwt.py", line 73, in func
    v = self.cache[key] = f(*args,**kwargs),time.time()
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Plex-0.1.0b0-py2.7.egg/mopidy_plex/library.py", line 46, in browse
    plexaudio.list_items(self.plex, '/library/sections/4/albums')]
AttributeError: 'module' object has no attribute 'list_items'

If I install the mopidy-plex version directly from pypi I don't see the errros at startup but the behavior is the same when trying to list artists/albums

-Jeff

**Comment by havardgulldahl** [comment]
Thank you for reporting this.

I have updated the repo to match some breaking api changes in `plexapi`, would please see if this fixes things for you?

**Comment by jrlambs** [comment]
This fixed the problem.... the next problem I ran into.. that I fixed manually is that the Music library on my plex installation is /sections/3 instead of /sections/4  .  I'm not sure if there's a reliable way to figure out which section is music without actually checking for the /sections/X/albums path actually exists or whatnot.... anyway.. I just went into the library.py file and changed the 4 to a 3 in the 2 places and everything works now.

**Comment by havardgulldahl** [comment]
ok, thanks. I'll look into the issue with the music secition. Closing this issue, please open a new bug report if you have a problem. Cheers!
